#!/bin/bash

#Identify all IP adresses which are part of the same subnet

BB=`ifconfig en0 | grep broadcast | awk '{print $6}'`
echo ${BB}
ping ${BB} -t 1
arp -a
#| awk '{print $2}' | grep `echo ${BB.//}`