#!/bin/bash

#Identify all IP adresses which are part of the same subnet

BB=`ifconfig en0 | awk '/broadcast/{print $6}'`
echo ${BB} #save the anwser to 'BB' variable
ping ${BB} -t 1 #timing for 1 sec
arp -a | awk '{print $2}' | grep `echo "${BB//.255}"` #output the anwser with only all the submask