#!/bin/bash

#Use the output of the previous command to find the name and IP address of the
#device that makes the link between you (local network) and the outside world

#NAT
#Network Adress Translation
#echo nat (10.60.1.1)

nat (10.60.1.1)