#!/bin/bash

# Figure out the PID of the SSHD service.

# sshd (OpenSSH Daemon) is the daemon program for ssh.
# sshd listens for connections from clients.
# It is normally started at boot from /etc/rc.
# It forks a new daemon for each incoming connection.
# The forked daemons handle key exchange, encryption,
# authentication, command execution, and data exchange.

# cat /var/run/sshd.pid

systemctl status ssh | awk '/PID/{print $3}'