#!/bin/bash

# Find the command that kills the background command’s process
# sudo - super user do give privilage to do more secured commands
# pkill - can specify what kind of process i want to terminate

sudo pkill 'tail'