#!/bin/bash

printf "\033[0;35mHello, what is your name?\n"

printf "\033[0mMy name is "
read name

printf "\033[0;35mGender?\n"

printf "\033[0mboy/girl: "
read gender

printf "\033[0;35mWhat is your favorite programming language?\n"

printf "\033[0mYour answer: "
read language

printf "\033[0;32mAnswers:\n"
printf "1. $name\n"
printf "2. $gender\n"
printf "3. $language\n"